insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD")  values(1,'Ampliacion');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (2,'Andador');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (3,'Avenida');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (4,'Boulevard');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (5,'Calle');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (6,'Callejon');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (7,'Calzada');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (8,'Cerrada');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (9,'Circuito');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (10,'Circunvalacion');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (11,'Continuacion');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (12,'Corredor');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (13,'Diagonal');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (14,'Eje vial');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (15,'Pasaje');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (16,'Peatonal');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (17,'Periferico');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (18,'Privada');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (19,'Prolongacion');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (20,'Retorno');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (21,'Viaducto');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (22,'Ninguno');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (23,'Carretera');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (24,'Brecha');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (25,'Camino');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (26,'Terraceria');
insert into validador_c_tp_vialidad ("CD_TIPO_VIALIDAD","NB_TIPO_VIALIDAD") values (27,'Vereda');