"""
Django settings for SDSPUBv1 project.

Generated by 'django-admin startproject' using Django 1.8.17.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '71ddq*wd-(^$!t!eiq%$)rdrto9-y=5o0j%t5wmak#43n70i$-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [#u'10.40.13.12',
                 u'localhost',
                 u'127.0.0.1']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'validador',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'SDSPUBv1.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'SDSPUBv1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'NAME': 'pub_sdstabasco',
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'USER': 'postgres',
        #'PASSWORD': 'postgres',
        'PASSWORD' : 'Postgres1',
	    #'HOST' : '10.40.13.14',
        'HOST' : 'sdspgtest.vmlocal',
	    'DATABASE_PORT' : '5432'
    },
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
    'C:/Users/DTIC-SYS/PycharmProjects/SDSPUBv1/static/'
#    '/home/epalomeque/PycharmProjects/PUBvalidador/static'
)

MEDIA_ROOT = 'C:/Users/DTIC-SYS/PycharmProjects/SDSPUBv1/_media/'
#MEDIA_ROOT = '/home/epalomeque/PycharmProjects/PUBvalidador/media/'

# Redirect when login is correct.
LOGIN_REDIRECT_URL = '/validador/home'
# Redirect when login is not correct.
LOGIN_URL = '/validador'

## email settings
EMAIL_BACKEND ='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'emmanuel@origamienlinea.com'
EMAIL_HOST_PASSWORD = 'EstaFacil123'
EMAIL_USE_SSL = True